[package]
name = "vclogg-core"
authors.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
aho-corasick.workspace = true
anyhow.workspace = true
chardetng = "0.1"
encoding_rs = "0.8"
memchr = "2.7"
memmap2 = "0.9"
regex = "1.11"
rayon.workspace = true
roaring.workspace = true
sha2.workspace = true

[target.'cfg(windows)'.dependencies]
windows-sys.workspace = true

[lints]
workspace = true
