[package]
name = "vclogg2"
authors.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "vclogg2"
path = "src/main.rs"

[features]
ui-performance-profiler = ["gpui/profiler"]

[dependencies]
aho-corasick.workspace = true
anyhow.workspace = true
async-channel.workspace = true
chrono.workspace = true
dirs.workspace = true
gpui.workspace = true
gpui-base.workspace = true
gpui-component.workspace = true
gpui-component-assets.workspace = true
gpui_platform.workspace = true
keyring.workspace = true
log.workspace = true
notify.workspace = true
reqwest.workspace = true
rayon.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
trash.workspace = true
url.workspace = true
uuid.workspace = true
vclogg-core = { path = "../vclogg-core" }
vclogg-data = { path = "../vclogg-data" }

[target.'cfg(windows)'.dependencies]
windows-sys = { workspace = true, features = ["Win32_System_LibraryLoader", "Win32_UI_WindowsAndMessaging"] }

[target.'cfg(any(windows, target_os = "linux"))'.dependencies]
raw-window-handle = "0.6.2"

[target.'cfg(target_os = "macos")'.dependencies]
objc2 = "0.6.4"
objc2-app-kit = { version = "0.3.2", default-features = false, features = ["std", "NSApplication", "NSImage"] }
objc2-foundation = { version = "0.3.2", default-features = false, features = ["std", "NSData"] }

[target.'cfg(target_os = "linux")'.dependencies]
image = { version = "0.25.10", default-features = false, features = ["png"] }
x11rb = "0.13.2"

[lints]
workspace = true

[dev-dependencies]
gpui = { workspace = true, features = ["test-support"] }

[build-dependencies]
semver.workspace = true

[target.'cfg(windows)'.build-dependencies]
embed-resource = "3"
