<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { api, jsonBody } from '../api'
import { useSessionStore } from '../store'
interface Administrator { id:string;username:string;status:string;createdAt:number;updatedAt:number;roleIds:string[] }
interface Role { id:string;name:string;builtIn:boolean }
const session=useSessionStore(),loading=ref(false),items=ref<Administrator[]>([]),roles=ref<Role[]>([]),total=ref(0),query=reactive({q:'',page:1,pageSize:30})
const dialog=ref(false),saving=ref(false),editing=ref<Administrator|null>(null),form=reactive({username:'',password:'',roleIds:[] as string[]})
const title=computed(()=>editing.value?'调整管理员':'创建管理员')
async function load(){loading.value=true;try{const p=new URLSearchParams(Object.entries(query).map(([k,v])=>[k,String(v)]));const [admins,roleData]=await Promise.all([api<{items:Administrator[];total:number}>(`/admin/api/administrators?${p}`),api<{items:Role[]}>('/admin/api/roles')]);items.value=admins.items;total.value=admins.total;roles.value=roleData.items}finally{loading.value=false}}
function openCreate(){editing.value=null;Object.assign(form,{username:'',password:'',roleIds:[]});dialog.value=true}
function openEdit(item:Administrator){editing.value=item;Object.assign(form,{username:item.username,password:'',roleIds:[...item.roleIds]});dialog.value=true}
async function save(){saving.value=true;try{if(editing.value){await api(`/admin/api/administrators/${editing.value.id}`,{method:'PATCH',body:jsonBody({roleIds:form.roleIds})})}else{await api('/admin/api/administrators',{method:'POST',body:jsonBody(form)})}dialog.value=false;ElMessage.success(editing.value?'管理员角色已更新':'管理员已创建');await load()}finally{saving.value=false}}
async function toggle(item:Administrator){const status=item.status==='active'?'disabled':'active';await ElMessageBox.confirm(status==='disabled'?`停用管理员“${item.username}”？`:`启用管理员“${item.username}”？`,'管理员状态',{type:'warning'});await api(`/admin/api/administrators/${item.id}`,{method:'PATCH',body:jsonBody({status})});ElMessage.success('管理员状态已更新');await load()}
async function resetPassword(item:Administrator){const result=await ElMessageBox.prompt(`为“${item.username}”设置不少于 10 个字符的新密码。`,'重置密码',{inputType:'password',inputValidator:value=>value.length>=10||'密码至少需要 10 个字符',confirmButtonText:'重置密码'});await api(`/admin/api/administrators/${item.id}/password`,{method:'PUT',body:jsonBody({password:result.value})});ElMessage.success('密码已重置，目标管理员的现有会话已撤销')}
const roleNames=(ids:string[])=>ids.map(id=>roles.value.find(role=>role.id===id)?.name||id)
onMounted(load)
</script>
<template><div class="page-stack"><div class="page-title-row"><div><h1>管理员</h1><p>创建后台账户，分配角色并控制登录状态。</p></div><el-button v-if="session.can('admins.create')" type="primary" @click="openCreate">创建管理员</el-button></div><section class="panel"><header class="panel-header"><div class="toolbar"><el-input v-model="query.q" class="search-input" clearable placeholder="搜索管理员账号" @keyup.enter="query.page=1;load()"/><el-button @click="query.page=1;load()">查询</el-button></div></header><el-table :data="items" v-loading="loading"><el-table-column label="管理员" min-width="210"><template #default="{row}"><div class="cell-main">{{row.username}}</div><div class="cell-sub">{{row.id===session.session?.id?'当前账户':row.id}}</div></template></el-table-column><el-table-column label="角色" min-width="230"><template #default="{row}"><el-tag v-for="name in roleNames(row.roleIds)" :key="name" effect="plain" style="margin-right:6px">{{name}}</el-tag></template></el-table-column><el-table-column label="状态" width="100"><template #default="{row}"><el-tag :type="row.status==='active'?'success':'info'">{{row.status==='active'?'启用':'停用'}}</el-tag></template></el-table-column><el-table-column label="创建时间" width="180"><template #default="{row}">{{new Date(row.createdAt).toLocaleString()}}</template></el-table-column><el-table-column label="操作" width="260" fixed="right"><template #default="{row}"><el-button v-if="session.can('admins.update')" link type="primary" @click="openEdit(row)">分配角色</el-button><el-button v-if="session.can('admins.update')" link :type="row.status==='active'?'danger':'success'" @click="toggle(row)">{{row.status==='active'?'停用':'启用'}}</el-button><el-button v-if="session.can('admins.reset_password')" link @click="resetPassword(row)">重置密码</el-button></template></el-table-column><template #empty><div class="empty-state"><strong>没有管理员</strong>创建第一个受控账户。</div></template></el-table><footer class="table-footer"><el-pagination v-model:current-page="query.page" v-model:page-size="query.pageSize" layout="total, prev, pager, next" :total="total" @change="load"/></footer></section><el-dialog v-model="dialog" :title="title" width="min(520px,92vw)"><el-form label-position="top"><el-form-item label="管理员账号"><el-input v-model="form.username" :disabled="Boolean(editing)" maxlength="64"/></el-form-item><el-form-item v-if="!editing" label="初始密码"><el-input v-model="form.password" type="password" show-password minlength="10"/></el-form-item><el-form-item label="角色"><el-select v-model="form.roleIds" multiple style="width:100%" placeholder="至少选择一个角色"><el-option v-for="role in roles" :key="role.id" :label="role.name" :value="role.id"/></el-select></el-form-item></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" :disabled="!form.roleIds.length||(!editing&&(!form.username.trim()||form.password.length<10))" :loading="saving" @click="save">{{editing?'保存角色':'创建管理员'}}</el-button></template></el-dialog></div></template>
