<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { api } from '../api'
interface Audit {id:number;username:string;action:string;resourceType:string;resourceId:string;result:string;clientAddress:string;metadata:unknown;createdAt:number}
const loading=ref(false),items=ref<Audit[]>([]),total=ref(0),query=reactive({username:'',action:'',result:'',page:1,pageSize:50})
async function load(){loading.value=true;try{const values=Object.entries(query).filter(([,v])=>v!==''),p=new URLSearchParams(values.map(([k,v])=>[k,String(v)]));const data=await api<{items:Audit[];total:number}>(`/admin/api/audit?${p}`);items.value=data.items;total.value=data.total}finally{loading.value=false}}
onMounted(load)
</script>
<template><div class="page-stack"><div class="page-title-row"><div><h1>操作审计</h1><p>追踪后台变更、登录事件和权限拒绝，不记录任何密码或令牌。</p></div></div><section class="panel"><header class="panel-header"><div class="toolbar"><el-input v-model="query.username" class="search-input" clearable placeholder="管理员账号" @keyup.enter="query.page=1;load()"/><el-input v-model="query.action" style="width:210px" clearable placeholder="动作，例如 role.update"/><el-select v-model="query.result" clearable placeholder="全部结果" style="width:130px"><el-option label="成功" value="success"/><el-option label="失败" value="failure"/><el-option label="拒绝" value="denied"/></el-select><el-button type="primary" @click="query.page=1;load()">查询</el-button></div></header><el-table :data="items" v-loading="loading"><el-table-column label="时间" width="180"><template #default="{row}">{{new Date(row.createdAt).toLocaleString()}}</template></el-table-column><el-table-column label="管理员" width="150"><template #default="{row}">{{row.username||'未认证请求'}}</template></el-table-column><el-table-column label="动作" min-width="190" prop="action"/><el-table-column label="资源" min-width="210"><template #default="{row}"><span>{{row.resourceType||'—'}}</span><div class="cell-sub">{{row.resourceId}}</div></template></el-table-column><el-table-column label="结果" width="90"><template #default="{row}"><el-tag :type="row.result==='success'?'success':row.result==='denied'?'warning':'danger'">{{row.result==='success'?'成功':row.result==='denied'?'拒绝':'失败'}}</el-tag></template></el-table-column><el-table-column label="来源" width="150" prop="clientAddress"/><el-table-column label="元数据" min-width="260"><template #default="{row}"><div class="metadata" :title="JSON.stringify(row.metadata)">{{JSON.stringify(row.metadata)}}</div></template></el-table-column><template #empty><div class="empty-state"><strong>没有审计记录</strong>新的管理操作会显示在这里。</div></template></el-table><footer class="table-footer"><el-pagination v-model:current-page="query.page" v-model:page-size="query.pageSize" layout="total, sizes, prev, pager, next" :total="total" :page-sizes="[20,50,100]" @change="load"/></footer></section></div></template>
