<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { api, jsonBody } from '../api'
import { useSessionStore } from '../store'
interface Identity { id:string;displayName:string;createdAt:number;lastSeenAt:number;revokedAt:number|null }
const session=useSessionStore(),loading=ref(false),items=ref<Identity[]>([]),total=ref(0),query=reactive({q:'',page:1,pageSize:30})
async function load(){loading.value=true;try{const p=new URLSearchParams(Object.entries(query).map(([k,v])=>[k,String(v)]));const data=await api<{items:Identity[];total:number}>(`/admin/api/identities?${p}`);items.value=data.items;total.value=data.total}finally{loading.value=false}}
async function toggle(item:Identity){const revoked=!item.revokedAt;await ElMessageBox.confirm(revoked?`撤销“${item.displayName}”的访问权限？`:`恢复“${item.displayName}”的访问权限？`,revoked?'撤销身份':'恢复身份',{type:revoked?'warning':'info'});await api(`/admin/api/identities/${item.id}`,{method:'PATCH',body:jsonBody({revoked})});ElMessage.success(revoked?'身份已撤销':'身份已恢复');await load()}
onMounted(load)
</script>
<template><div class="page-stack"><div class="page-title-row"><div><h1>访问身份</h1><p>查看客户端注册和活跃情况，及时撤销异常身份。</p></div></div><section class="panel"><header class="panel-header"><div class="toolbar"><el-input v-model="query.q" class="search-input" clearable placeholder="搜索工号或昵称" @keyup.enter="query.page=1;load()"/><el-button type="primary" @click="query.page=1;load()">查询</el-button></div></header><el-table :data="items" v-loading="loading"><el-table-column label="工号 / 昵称" min-width="220"><template #default="{row}"><div class="cell-main">{{row.displayName}}</div><div class="cell-sub">{{row.id}}</div></template></el-table-column><el-table-column label="创建时间" width="180"><template #default="{row}">{{new Date(row.createdAt).toLocaleString()}}</template></el-table-column><el-table-column label="最后访问" width="180"><template #default="{row}">{{new Date(row.lastSeenAt).toLocaleString()}}</template></el-table-column><el-table-column label="状态" width="110"><template #default="{row}"><el-tag :type="row.revokedAt?'danger':'success'">{{row.revokedAt?'已撤销':'正常'}}</el-tag></template></el-table-column><el-table-column label="操作" width="120" fixed="right"><template #default="{row}"><el-button v-if="session.can('identities.revoke')" link :type="row.revokedAt?'success':'danger'" @click="toggle(row)">{{row.revokedAt?'恢复':'撤销'}}</el-button></template></el-table-column><template #empty><div class="empty-state"><strong>没有找到访问身份</strong>尝试使用其他搜索内容。</div></template></el-table><footer class="table-footer"><el-pagination v-model:current-page="query.page" v-model:page-size="query.pageSize" layout="total, sizes, prev, pager, next" :total="total" :page-sizes="[20,30,50,100]" @change="load"/></footer></section></div></template>
