<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { api, jsonBody } from '../api'
import { useSessionStore } from '../store'
interface Permission { code:string;name:string;group:string;description:string }
interface Role { id:string;name:string;description:string;builtIn:boolean;permissions:string[];memberCount:number }
const session=useSessionStore(),loading=ref(false),roles=ref<Role[]>([]),permissions=ref<Permission[]>([]),dialog=ref(false),saving=ref(false),editing=ref<Role|null>(null)
const form=reactive({name:'',description:'',permissions:[] as string[]})
const groups=computed(()=>{const map=new Map<string,Permission[]>();for(const item of permissions.value)map.set(item.group,[...(map.get(item.group)||[]),item]);return [...map.entries()]})
async function load(){loading.value=true;try{const [roleData,permissionData]=await Promise.all([api<{items:Role[]}>('/admin/api/roles'),api<{items:Permission[]}>('/admin/api/permissions')]);roles.value=roleData.items;permissions.value=permissionData.items}finally{loading.value=false}}
function openCreate(){editing.value=null;Object.assign(form,{name:'',description:'',permissions:[]});dialog.value=true}
function openEdit(role:Role){editing.value=role;Object.assign(form,{name:role.name,description:role.description,permissions:[...role.permissions]});dialog.value=true}
async function save(){saving.value=true;try{const payload={name:form.name,description:form.description,permissions:form.permissions};if(editing.value)await api(`/admin/api/roles/${editing.value.id}`,{method:'PUT',body:jsonBody(payload)});else await api('/admin/api/roles',{method:'POST',body:jsonBody(payload)});dialog.value=false;ElMessage.success(editing.value?'角色已更新':'角色已创建');await load()}finally{saving.value=false}}
async function remove(role:Role){await ElMessageBox.confirm(`确定删除角色“${role.name}”吗？`,'删除角色',{type:'warning'});await api(`/admin/api/roles/${role.id}`,{method:'DELETE'});ElMessage.success('角色已删除');await load()}
onMounted(load)
</script>
<template><div class="page-stack"><div class="page-title-row"><div><h1>角色权限</h1><p>通过稳定权限代码控制菜单、按钮和服务端 API。</p></div><el-button v-if="session.can('roles.create')" type="primary" @click="openCreate">创建角色</el-button></div><section class="panel"><el-table :data="roles" v-loading="loading"><el-table-column label="角色" min-width="210"><template #default="{row}"><div class="cell-main">{{row.name}} <el-tag v-if="row.builtIn" size="small" effect="plain">内置</el-tag></div><div class="cell-sub">{{row.description||'暂无说明'}}</div></template></el-table-column><el-table-column label="成员" width="100"><template #default="{row}">{{row.memberCount}} 人</template></el-table-column><el-table-column label="权限" min-width="280"><template #default="{row}"><span class="cell-sub">{{row.permissions.length}} 项权限</span><div style="margin-top:6px"><el-tag v-for="code in row.permissions.slice(0,4)" :key="code" size="small" effect="plain" style="margin:0 5px 5px 0">{{code}}</el-tag><el-tag v-if="row.permissions.length>4" size="small">+{{row.permissions.length-4}}</el-tag></div></template></el-table-column><el-table-column label="操作" width="150" fixed="right"><template #default="{row}"><el-button v-if="session.can('roles.update')&&!row.builtIn" link type="primary" @click="openEdit(row)">编辑</el-button><el-button v-if="session.can('roles.delete')&&!row.builtIn" link type="danger" :disabled="row.memberCount>0" @click="remove(row)">删除</el-button></template></el-table-column></el-table></section><el-dialog v-model="dialog" :title="editing?'编辑角色':'创建角色'" width="min(720px,94vw)"><el-form label-position="top"><el-form-item label="角色名称"><el-input v-model="form.name" maxlength="64"/></el-form-item><el-form-item label="角色说明"><el-input v-model="form.description" type="textarea" :rows="2" maxlength="500"/></el-form-item><el-form-item label="权限配置"><div class="permission-groups" style="width:100%"><section v-for="[group,items] in groups" :key="group" class="permission-group"><h4>{{group}}</h4><el-checkbox-group v-model="form.permissions" class="permission-list"><el-checkbox v-for="item in items" :key="item.code" :value="item.code"><span :title="item.description">{{item.name}}</span></el-checkbox></el-checkbox-group></section></div></el-form-item></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" :disabled="!form.name.trim()||!form.permissions.length" :loading="saving" @click="save">保存角色</el-button></template></el-dialog></div></template>
